Integer_list = []


def User_Input():
    for i in range(1, 11):
        Integer_list.append(int(input(f"Enter Integer {i} : ")))

    return Integer_list


def maximum():
    Pointer_1 = 0
    Pointer_2 = len(Integer_list) - 1

    while Pointer_1 != Pointer_2:

        if Integer_list[Pointer_1] < Integer_list[Pointer_2]:
            Pointer_1 += 1

        elif Integer_list[Pointer_1] > Integer_list[Pointer_2]:
            Pointer_2 -= 1

        else:
            Pointer_1 += 1

    return Integer_list[Pointer_1]


def Minimum():
    Pointer_1 = 0
    Pointer_2 = len(Integer_list) - 1

    while Pointer_1 < Pointer_2:

        if Integer_list[Pointer_1] > Integer_list[Pointer_2]:
            Pointer_1 += 1

        elif Integer_list[Pointer_1] < Integer_list[Pointer_2]:
            Pointer_2 -= 1

        else:
            Pointer_1 += 1

    return Integer_list[Pointer_1]


def Average():
    total_sum = 0

    for i in range(0, len(Integer_list)):
        total_sum += Integer_list[i]

    avg = total_sum / len(Integer_list)

    return avg


def ascending():

    Ascending_Integer_list = Integer_list[:]

    left = 0
    right = 1

    while left < len(Ascending_Integer_list) - 1:

        if Ascending_Integer_list[left] > Ascending_Integer_list[right]:

            Ascending_Integer_list[left], Ascending_Integer_list[right] = Ascending_Integer_list[right], Ascending_Integer_list[left]

        right += 1

        if right == len(Ascending_Integer_list):
            left += 1
            right = left + 1

    return Ascending_Integer_list


def descending():

    Descending_Integer_list = Integer_list[:]

    left = 0
    right = 1

    while left < len(Descending_Integer_list) - 1:

        if Descending_Integer_list[left] < Descending_Integer_list[right]:

            Descending_Integer_list[left], Descending_Integer_list[right] = Descending_Integer_list[right], Descending_Integer_list[left]

        right += 1

        if right == len(Descending_Integer_list):
            left += 1
            right = left + 1

    return Descending_Integer_list


def Add_Item():

    Integer_list.append(int(input("Enter an Element to Add it in List : ")))

    return Integer_list


def delete_item():

    Integer_list.pop(0)

    return Integer_list


if __name__ == "__main__":

    User_Inputs = User_Input()
    print(f"\nThe List Generated By User Inputs are : {User_Inputs}")

    Max = maximum()
    print(f"\nThe Maximum Element in the List is : {Max}")
    
    Min = Minimum()
    print(f"\nThe Smallest Element in the List is : {Min}")
    
    Avg = Average()
    print(f"\nThe Average of the List is : {Avg}")
    
    Asc = ascending()
    print(f"\nList in Ascending Order : {Asc}")
    
    Des = descending()
    print(f"\nList in Descending Order : {Des}")

    Add = Add_Item()
    print(f"\nList after adding New Element : {Add}")
    
    Del = delete_item()
    print(f"\nList after removing first element : {Del}")
